/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rendezvous2k13;

/**
 *
 * @author Gowtham
 */
public class welcome_panel extends javax.swing.JPanel {

    /**
     * Creates new form welcome_panel
     */
    public welcome_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rendezvous_label = new javax.swing.JLabel();
        welcome_label = new javax.swing.JLabel();
        start_button = new javax.swing.JButton();
        inst_button = new javax.swing.JButton();

        rendezvous_label.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        rendezvous_label.setForeground(new java.awt.Color(0, 153, 0));
        rendezvous_label.setText(" Rendezvous 2k13");

        welcome_label.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        welcome_label.setForeground(new java.awt.Color(204, 0, 0));
        welcome_label.setText("Welcome to ReTread !!");

        start_button.setText("Start");
        start_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_buttonActionPerformed(evt);
            }
        });

        inst_button.setText("Instructions");
        inst_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inst_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(inst_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(start_button)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rendezvous_label)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(welcome_label)))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(rendezvous_label)
                .addGap(88, 88, 88)
                .addComponent(welcome_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start_button)
                    .addComponent(inst_button))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inst_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inst_buttonActionPerformed
        // TODO add your handling code here:
        instructions_frame ins=new instructions_frame();
        ins.setVisible(true);
        ins.pack();
        
        
    }//GEN-LAST:event_inst_buttonActionPerformed

    private void start_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_buttonActionPerformed
        // TODO add your handling code here:
        memberdetails_panel mdp=new memberdetails_panel();
        Rendezvous2k13.mainframe.getContentPane().removeAll();
        Rendezvous2k13.mainframe.add(mdp);
        Rendezvous2k13.mainframe.validate();
        Rendezvous2k13.mainframe.repaint();
        Rendezvous2k13.mainframe.pack();
        
    }//GEN-LAST:event_start_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inst_button;
    private javax.swing.JLabel rendezvous_label;
    private javax.swing.JButton start_button;
    private javax.swing.JLabel welcome_label;
    // End of variables declaration//GEN-END:variables
}
